AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SaaS QR Menu Order Service Backend

Resources:
  # 1. DATABASE: The DynamoDB Table
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: orders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shopId
          AttributeType: S
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: shopId  # Partition Key (PK)
          KeyType: HASH
        - AttributeName: orderId # Sort Key (SK)
          KeyType: RANGE

  # 2. BACKEND: The Java Lambda Function
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/qrmenu-order-service-1.0-SNAPSHOT.jar
      Handler: com.qrmenu.orders.handlers.CreateOrderHandler::handleRequest
      Runtime: java21
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        CreateOrderApi:
          Type: Api
          Properties:
            Path: /orders
            Method: post

  GetOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/qrmenu-order-service-1.0-SNAPSHOT.jar
      Handler: com.qrmenu.orders.handlers.GetOrdersHandler::handleRequest
      Runtime: java21
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
      Policies:
        # Notice we only give READ policy here, for security!
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        GetOrdersApi:
          Type: Api
          Properties:
            Path: /orders
            Method: get

  UpdateOrderStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/qrmenu-order-service-1.0-SNAPSHOT.jar
      Handler: com.qrmenu.orders.handlers.UpdateOrderStatusHandler::handleRequest
      Runtime: java21
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          ORDERS_TABLE: orders
      Policies:
        - DynamoDBWritePolicy:
            TableName: orders
      Events:
        UpdateOrderApi:
          Type: Api
          Properties:
            Path: /orders/status
            Method: patch

  # GET MENU

  GetMenuFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/qrmenu-order-service-1.0-SNAPSHOT.jar
      Handler: com.qrmenu.orders.handlers.GetMenuHandler::handleRequest
      Runtime: java21
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          MENUS_TABLE: Menus
      Policies:
        - DynamoDBReadPolicy:
            TableName: Menus
      Events:
        GetMenuApi:
          Type: Api
          Properties:
            Path: /menu
            Method: get



# 3. OUTPUTS: This must be completely to the left, same level as Resources
Outputs:
  OrderApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"